require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DairyPlansController do

  # This should return the minimal set of attributes required to create a valid
  # DairyPlan. As you add validations to DairyPlan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DairyPlansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dairy_plans as @dairy_plans" do
      dairy_plan = DairyPlan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dairy_plans).should eq([dairy_plan])
    end
  end

  describe "GET show" do
    it "assigns the requested dairy_plan as @dairy_plan" do
      dairy_plan = DairyPlan.create! valid_attributes
      get :show, {:id => dairy_plan.to_param}, valid_session
      assigns(:dairy_plan).should eq(dairy_plan)
    end
  end

  describe "GET new" do
    it "assigns a new dairy_plan as @dairy_plan" do
      get :new, {}, valid_session
      assigns(:dairy_plan).should be_a_new(DairyPlan)
    end
  end

  describe "GET edit" do
    it "assigns the requested dairy_plan as @dairy_plan" do
      dairy_plan = DairyPlan.create! valid_attributes
      get :edit, {:id => dairy_plan.to_param}, valid_session
      assigns(:dairy_plan).should eq(dairy_plan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DairyPlan" do
        expect {
          post :create, {:dairy_plan => valid_attributes}, valid_session
        }.to change(DairyPlan, :count).by(1)
      end

      it "assigns a newly created dairy_plan as @dairy_plan" do
        post :create, {:dairy_plan => valid_attributes}, valid_session
        assigns(:dairy_plan).should be_a(DairyPlan)
        assigns(:dairy_plan).should be_persisted
      end

      it "redirects to the created dairy_plan" do
        post :create, {:dairy_plan => valid_attributes}, valid_session
        response.should redirect_to(DairyPlan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dairy_plan as @dairy_plan" do
        # Trigger the behavior that occurs when invalid params are submitted
        DairyPlan.any_instance.stub(:save).and_return(false)
        post :create, {:dairy_plan => {}}, valid_session
        assigns(:dairy_plan).should be_a_new(DairyPlan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DairyPlan.any_instance.stub(:save).and_return(false)
        post :create, {:dairy_plan => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dairy_plan" do
        dairy_plan = DairyPlan.create! valid_attributes
        # Assuming there are no other dairy_plans in the database, this
        # specifies that the DairyPlan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DairyPlan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dairy_plan.to_param, :dairy_plan => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dairy_plan as @dairy_plan" do
        dairy_plan = DairyPlan.create! valid_attributes
        put :update, {:id => dairy_plan.to_param, :dairy_plan => valid_attributes}, valid_session
        assigns(:dairy_plan).should eq(dairy_plan)
      end

      it "redirects to the dairy_plan" do
        dairy_plan = DairyPlan.create! valid_attributes
        put :update, {:id => dairy_plan.to_param, :dairy_plan => valid_attributes}, valid_session
        response.should redirect_to(dairy_plan)
      end
    end

    describe "with invalid params" do
      it "assigns the dairy_plan as @dairy_plan" do
        dairy_plan = DairyPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DairyPlan.any_instance.stub(:save).and_return(false)
        put :update, {:id => dairy_plan.to_param, :dairy_plan => {}}, valid_session
        assigns(:dairy_plan).should eq(dairy_plan)
      end

      it "re-renders the 'edit' template" do
        dairy_plan = DairyPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DairyPlan.any_instance.stub(:save).and_return(false)
        put :update, {:id => dairy_plan.to_param, :dairy_plan => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dairy_plan" do
      dairy_plan = DairyPlan.create! valid_attributes
      expect {
        delete :destroy, {:id => dairy_plan.to_param}, valid_session
      }.to change(DairyPlan, :count).by(-1)
    end

    it "redirects to the dairy_plans list" do
      dairy_plan = DairyPlan.create! valid_attributes
      delete :destroy, {:id => dairy_plan.to_param}, valid_session
      response.should redirect_to(dairy_plans_url)
    end
  end

end
