require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExtAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # ExtAttribute. As you add validations to ExtAttribute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExtAttributesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ext_attributes as @ext_attributes" do
      ext_attribute = ExtAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ext_attributes).should eq([ext_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested ext_attribute as @ext_attribute" do
      ext_attribute = ExtAttribute.create! valid_attributes
      get :show, {:id => ext_attribute.to_param}, valid_session
      assigns(:ext_attribute).should eq(ext_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new ext_attribute as @ext_attribute" do
      get :new, {}, valid_session
      assigns(:ext_attribute).should be_a_new(ExtAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested ext_attribute as @ext_attribute" do
      ext_attribute = ExtAttribute.create! valid_attributes
      get :edit, {:id => ext_attribute.to_param}, valid_session
      assigns(:ext_attribute).should eq(ext_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExtAttribute" do
        expect {
          post :create, {:ext_attribute => valid_attributes}, valid_session
        }.to change(ExtAttribute, :count).by(1)
      end

      it "assigns a newly created ext_attribute as @ext_attribute" do
        post :create, {:ext_attribute => valid_attributes}, valid_session
        assigns(:ext_attribute).should be_a(ExtAttribute)
        assigns(:ext_attribute).should be_persisted
      end

      it "redirects to the created ext_attribute" do
        post :create, {:ext_attribute => valid_attributes}, valid_session
        response.should redirect_to(ExtAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ext_attribute as @ext_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExtAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:ext_attribute => {}}, valid_session
        assigns(:ext_attribute).should be_a_new(ExtAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExtAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:ext_attribute => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ext_attribute" do
        ext_attribute = ExtAttribute.create! valid_attributes
        # Assuming there are no other ext_attributes in the database, this
        # specifies that the ExtAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExtAttribute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ext_attribute.to_param, :ext_attribute => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ext_attribute as @ext_attribute" do
        ext_attribute = ExtAttribute.create! valid_attributes
        put :update, {:id => ext_attribute.to_param, :ext_attribute => valid_attributes}, valid_session
        assigns(:ext_attribute).should eq(ext_attribute)
      end

      it "redirects to the ext_attribute" do
        ext_attribute = ExtAttribute.create! valid_attributes
        put :update, {:id => ext_attribute.to_param, :ext_attribute => valid_attributes}, valid_session
        response.should redirect_to(ext_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the ext_attribute as @ext_attribute" do
        ext_attribute = ExtAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExtAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => ext_attribute.to_param, :ext_attribute => {}}, valid_session
        assigns(:ext_attribute).should eq(ext_attribute)
      end

      it "re-renders the 'edit' template" do
        ext_attribute = ExtAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExtAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => ext_attribute.to_param, :ext_attribute => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ext_attribute" do
      ext_attribute = ExtAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => ext_attribute.to_param}, valid_session
      }.to change(ExtAttribute, :count).by(-1)
    end

    it "redirects to the ext_attributes list" do
      ext_attribute = ExtAttribute.create! valid_attributes
      delete :destroy, {:id => ext_attribute.to_param}, valid_session
      response.should redirect_to(ext_attributes_url)
    end
  end

end
