require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeachingProblemsController do

  # This should return the minimal set of attributes required to create a valid
  # TeachingProblem. As you add validations to TeachingProblem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeachingProblemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all teaching_problems as @teaching_problems" do
      teaching_problem = TeachingProblem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:teaching_problems).should eq([teaching_problem])
    end
  end

  describe "GET show" do
    it "assigns the requested teaching_problem as @teaching_problem" do
      teaching_problem = TeachingProblem.create! valid_attributes
      get :show, {:id => teaching_problem.to_param}, valid_session
      assigns(:teaching_problem).should eq(teaching_problem)
    end
  end

  describe "GET new" do
    it "assigns a new teaching_problem as @teaching_problem" do
      get :new, {}, valid_session
      assigns(:teaching_problem).should be_a_new(TeachingProblem)
    end
  end

  describe "GET edit" do
    it "assigns the requested teaching_problem as @teaching_problem" do
      teaching_problem = TeachingProblem.create! valid_attributes
      get :edit, {:id => teaching_problem.to_param}, valid_session
      assigns(:teaching_problem).should eq(teaching_problem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeachingProblem" do
        expect {
          post :create, {:teaching_problem => valid_attributes}, valid_session
        }.to change(TeachingProblem, :count).by(1)
      end

      it "assigns a newly created teaching_problem as @teaching_problem" do
        post :create, {:teaching_problem => valid_attributes}, valid_session
        assigns(:teaching_problem).should be_a(TeachingProblem)
        assigns(:teaching_problem).should be_persisted
      end

      it "redirects to the created teaching_problem" do
        post :create, {:teaching_problem => valid_attributes}, valid_session
        response.should redirect_to(TeachingProblem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teaching_problem as @teaching_problem" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingProblem.any_instance.stub(:save).and_return(false)
        post :create, {:teaching_problem => {}}, valid_session
        assigns(:teaching_problem).should be_a_new(TeachingProblem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingProblem.any_instance.stub(:save).and_return(false)
        post :create, {:teaching_problem => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teaching_problem" do
        teaching_problem = TeachingProblem.create! valid_attributes
        # Assuming there are no other teaching_problems in the database, this
        # specifies that the TeachingProblem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeachingProblem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => teaching_problem.to_param, :teaching_problem => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested teaching_problem as @teaching_problem" do
        teaching_problem = TeachingProblem.create! valid_attributes
        put :update, {:id => teaching_problem.to_param, :teaching_problem => valid_attributes}, valid_session
        assigns(:teaching_problem).should eq(teaching_problem)
      end

      it "redirects to the teaching_problem" do
        teaching_problem = TeachingProblem.create! valid_attributes
        put :update, {:id => teaching_problem.to_param, :teaching_problem => valid_attributes}, valid_session
        response.should redirect_to(teaching_problem)
      end
    end

    describe "with invalid params" do
      it "assigns the teaching_problem as @teaching_problem" do
        teaching_problem = TeachingProblem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingProblem.any_instance.stub(:save).and_return(false)
        put :update, {:id => teaching_problem.to_param, :teaching_problem => {}}, valid_session
        assigns(:teaching_problem).should eq(teaching_problem)
      end

      it "re-renders the 'edit' template" do
        teaching_problem = TeachingProblem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingProblem.any_instance.stub(:save).and_return(false)
        put :update, {:id => teaching_problem.to_param, :teaching_problem => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teaching_problem" do
      teaching_problem = TeachingProblem.create! valid_attributes
      expect {
        delete :destroy, {:id => teaching_problem.to_param}, valid_session
      }.to change(TeachingProblem, :count).by(-1)
    end

    it "redirects to the teaching_problems list" do
      teaching_problem = TeachingProblem.create! valid_attributes
      delete :destroy, {:id => teaching_problem.to_param}, valid_session
      response.should redirect_to(teaching_problems_url)
    end
  end

end
