require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VocabularyMeaningsController do

  # This should return the minimal set of attributes required to create a valid
  # VocabularyMeaning. As you add validations to VocabularyMeaning, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VocabularyMeaningsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vocabulary_meanings as @vocabulary_meanings" do
      vocabulary_meaning = VocabularyMeaning.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vocabulary_meanings).should eq([vocabulary_meaning])
    end
  end

  describe "GET show" do
    it "assigns the requested vocabulary_meaning as @vocabulary_meaning" do
      vocabulary_meaning = VocabularyMeaning.create! valid_attributes
      get :show, {:id => vocabulary_meaning.to_param}, valid_session
      assigns(:vocabulary_meaning).should eq(vocabulary_meaning)
    end
  end

  describe "GET new" do
    it "assigns a new vocabulary_meaning as @vocabulary_meaning" do
      get :new, {}, valid_session
      assigns(:vocabulary_meaning).should be_a_new(VocabularyMeaning)
    end
  end

  describe "GET edit" do
    it "assigns the requested vocabulary_meaning as @vocabulary_meaning" do
      vocabulary_meaning = VocabularyMeaning.create! valid_attributes
      get :edit, {:id => vocabulary_meaning.to_param}, valid_session
      assigns(:vocabulary_meaning).should eq(vocabulary_meaning)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VocabularyMeaning" do
        expect {
          post :create, {:vocabulary_meaning => valid_attributes}, valid_session
        }.to change(VocabularyMeaning, :count).by(1)
      end

      it "assigns a newly created vocabulary_meaning as @vocabulary_meaning" do
        post :create, {:vocabulary_meaning => valid_attributes}, valid_session
        assigns(:vocabulary_meaning).should be_a(VocabularyMeaning)
        assigns(:vocabulary_meaning).should be_persisted
      end

      it "redirects to the created vocabulary_meaning" do
        post :create, {:vocabulary_meaning => valid_attributes}, valid_session
        response.should redirect_to(VocabularyMeaning.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vocabulary_meaning as @vocabulary_meaning" do
        # Trigger the behavior that occurs when invalid params are submitted
        VocabularyMeaning.any_instance.stub(:save).and_return(false)
        post :create, {:vocabulary_meaning => {}}, valid_session
        assigns(:vocabulary_meaning).should be_a_new(VocabularyMeaning)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VocabularyMeaning.any_instance.stub(:save).and_return(false)
        post :create, {:vocabulary_meaning => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vocabulary_meaning" do
        vocabulary_meaning = VocabularyMeaning.create! valid_attributes
        # Assuming there are no other vocabulary_meanings in the database, this
        # specifies that the VocabularyMeaning created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VocabularyMeaning.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vocabulary_meaning.to_param, :vocabulary_meaning => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vocabulary_meaning as @vocabulary_meaning" do
        vocabulary_meaning = VocabularyMeaning.create! valid_attributes
        put :update, {:id => vocabulary_meaning.to_param, :vocabulary_meaning => valid_attributes}, valid_session
        assigns(:vocabulary_meaning).should eq(vocabulary_meaning)
      end

      it "redirects to the vocabulary_meaning" do
        vocabulary_meaning = VocabularyMeaning.create! valid_attributes
        put :update, {:id => vocabulary_meaning.to_param, :vocabulary_meaning => valid_attributes}, valid_session
        response.should redirect_to(vocabulary_meaning)
      end
    end

    describe "with invalid params" do
      it "assigns the vocabulary_meaning as @vocabulary_meaning" do
        vocabulary_meaning = VocabularyMeaning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VocabularyMeaning.any_instance.stub(:save).and_return(false)
        put :update, {:id => vocabulary_meaning.to_param, :vocabulary_meaning => {}}, valid_session
        assigns(:vocabulary_meaning).should eq(vocabulary_meaning)
      end

      it "re-renders the 'edit' template" do
        vocabulary_meaning = VocabularyMeaning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VocabularyMeaning.any_instance.stub(:save).and_return(false)
        put :update, {:id => vocabulary_meaning.to_param, :vocabulary_meaning => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vocabulary_meaning" do
      vocabulary_meaning = VocabularyMeaning.create! valid_attributes
      expect {
        delete :destroy, {:id => vocabulary_meaning.to_param}, valid_session
      }.to change(VocabularyMeaning, :count).by(-1)
    end

    it "redirects to the vocabulary_meanings list" do
      vocabulary_meaning = VocabularyMeaning.create! valid_attributes
      delete :destroy, {:id => vocabulary_meaning.to_param}, valid_session
      response.should redirect_to(vocabulary_meanings_url)
    end
  end

end
